import { Usuario, Equipo, Reserva, ModuloHorario } from '../tipos';

const obtenerFechaIso = (diasOffset: number = 0): string => {
  const hoy = new Date();
  hoy.setDate(hoy.getDate() + diasOffset);
  return hoy.toISOString().split('T')[0];
};

export const MODULOS_HORARIOS_LISTA: ModuloHorario[] = [
  'Módulo 1 (07:30 - 08:50)',
  'Módulo 2 (09:00 - 10:20)',
  'Módulo 3 (10:30 - 11:50)',
  'Módulo 4 (13:30 - 14:50)',
  'Módulo 5 (15:00 - 16:20)',
  'Módulo 6 (16:30 - 17:50)',
];

export const USUARIOS_INICIALES: Usuario[] = [
  {
    id: 1,
    nombre: 'Lucía Méndez',
    email: 'lucia.mendez@horizonte.edu.ar',
    rol: 'BIBLIOTECARIA',
  },
  {
    id: 2,
    nombre: 'Prof. Martín Gómez',
    email: 'martin.gomez@horizonte.edu.ar',
    rol: 'DOCENTE',
  },
  {
    id: 3,
    nombre: 'Prof. Mariana Castro',
    email: 'mariana.castro@horizonte.edu.ar',
    rol: 'DOCENTE',
  },
  {
    id: 4,
    nombre: 'Prof. Carlos Benítez',
    email: 'carlos.benitez@horizonte.edu.ar',
    rol: 'DOCENTE',
  },
];

export const EQUIPOS_INICIALES: Equipo[] = [
  {
    id: 1,
    nombre: 'Proyector Epson PowerLite 1',
    tipo: 'PROYECTOR',
    estado: 'DISPONIBLE',
    descripcion: 'HDMI 3600 lúmenes - Sala Audiovisual Principal',
    creadoEn: '2026-03-01T08:00:00Z',
  },
  {
    id: 2,
    nombre: 'Proyector Epson PowerLite 2',
    tipo: 'PROYECTOR',
    estado: 'DISPONIBLE',
    descripcion: 'HDMI 3300 lúmenes - Portátil para Aulas',
    creadoEn: '2026-03-01T08:00:00Z',
  },
  {
    id: 3,
    nombre: 'Proyector BenQ Aula Magna',
    tipo: 'PROYECTOR',
    estado: 'EN_MANTENIMIENTO',
    descripcion: 'En revisión de lámpara y filtro de polvo',
    creadoEn: '2026-03-02T09:00:00Z',
  },
  {
    id: 4,
    nombre: 'Notebook Dell Latitude 01',
    tipo: 'NOTEBOOK',
    estado: 'DISPONIBLE',
    descripcion: 'Intel Core i5, 16GB RAM, SSD 512GB - Carro Móvil',
    creadoEn: '2026-03-01T08:00:00Z',
  },
  {
    id: 5,
    nombre: 'Notebook Dell Latitude 02',
    tipo: 'NOTEBOOK',
    estado: 'DISPONIBLE',
    descripcion: 'Intel Core i5, 16GB RAM, SSD 512GB - Carro Móvil',
    creadoEn: '2026-03-01T08:00:00Z',
  },
  {
    id: 6,
    nombre: 'Notebook HP ProBook 03',
    tipo: 'NOTEBOOK',
    estado: 'DISPONIBLE',
    descripcion: 'AMD Ryzen 5, 8GB RAM, SSD 256GB - Aula Informática',
    creadoEn: '2026-03-03T10:00:00Z',
  },
  {
    id: 7,
    nombre: 'Notebook Lenovo ThinkPad 04',
    tipo: 'NOTEBOOK',
    estado: 'EN_MANTENIMIENTO',
    descripcion: 'Cambio de transformador y mantenimiento preventivo',
    creadoEn: '2026-03-04T11:00:00Z',
  },
];

export const RESERVAS_INICIALES: Reserva[] = [
  {
    id: 101,
    usuarioId: 2,
    usuarioNombre: 'Prof. Martín Gómez',
    usuarioEmail: 'martin.gomez@horizonte.edu.ar',
    equipoId: 1,
    equipoNombre: 'Proyector Epson PowerLite 1',
    equipoTipo: 'PROYECTOR',
    fecha: obtenerFechaIso(0),
    moduloHorario: 'Módulo 1 (07:30 - 08:50)',
    estado: 'CONFIRMADA',
    motivo: 'Clase de Historia - Proyección documental Siglo XX',
    creadoEn: new Date(Date.now() - 3600000 * 5).toISOString(),
    actualizadoEn: new Date(Date.now() - 3600000 * 4).toISOString(),
  },
  {
    id: 102,
    usuarioId: 3,
    usuarioNombre: 'Prof. Mariana Castro',
    usuarioEmail: 'mariana.castro@horizonte.edu.ar',
    equipoId: 1,
    equipoNombre: 'Proyector Epson PowerLite 1',
    equipoTipo: 'PROYECTOR',
    fecha: obtenerFechaIso(0),
    moduloHorario: 'Módulo 1 (07:30 - 08:50)',
    estado: 'RECHAZADA',
    motivo: 'Rechazo automático: recurso asignado a reserva #101 (Prof. Martín Gómez)',
    creadoEn: new Date(Date.now() - 3600000 * 3).toISOString(),
    actualizadoEn: new Date(Date.now() - 3600000 * 2).toISOString(),
  },
  {
    id: 103,
    usuarioId: 2,
    usuarioNombre: 'Prof. Martín Gómez',
    usuarioEmail: 'martin.gomez@horizonte.edu.ar',
    equipoId: 4,
    equipoNombre: 'Notebook Dell Latitude 01',
    equipoTipo: 'NOTEBOOK',
    fecha: obtenerFechaIso(0),
    moduloHorario: 'Módulo 2 (09:00 - 10:20)',
    estado: 'CONFIRMADA',
    motivo: 'Evaluación digital con formularios interactivos',
    creadoEn: new Date(Date.now() - 3600000 * 6).toISOString(),
  },
  {
    id: 104,
    usuarioId: 3,
    usuarioNombre: 'Prof. Mariana Castro',
    usuarioEmail: 'mariana.castro@horizonte.edu.ar',
    equipoId: 2,
    equipoNombre: 'Proyector Epson PowerLite 2',
    equipoTipo: 'PROYECTOR',
    fecha: obtenerFechaIso(0),
    moduloHorario: 'Módulo 2 (09:00 - 10:20)',
    estado: 'PENDIENTE',
    motivo: 'Presentación de Biología: Estructura y división celular',
    creadoEn: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: 105,
    usuarioId: 4,
    usuarioNombre: 'Prof. Carlos Benítez',
    usuarioEmail: 'carlos.benitez@horizonte.edu.ar',
    equipoId: 5,
    equipoNombre: 'Notebook Dell Latitude 02',
    equipoTipo: 'NOTEBOOK',
    fecha: obtenerFechaIso(1),
    moduloHorario: 'Módulo 3 (10:30 - 11:50)',
    estado: 'PENDIENTE',
    motivo: 'Taller de programación en Scratch para 2do año',
    creadoEn: new Date(Date.now() - 900000).toISOString(),
  },
  {
    id: 106,
    usuarioId: 3,
    usuarioNombre: 'Prof. Mariana Castro',
    usuarioEmail: 'mariana.castro@horizonte.edu.ar',
    equipoId: 5,
    equipoNombre: 'Notebook Dell Latitude 02',
    equipoTipo: 'NOTEBOOK',
    fecha: obtenerFechaIso(1),
    moduloHorario: 'Módulo 3 (10:30 - 11:50)',
    estado: 'PENDIENTE',
    motivo: 'Investigación guiada de laboratorio',
    creadoEn: new Date(Date.now() - 600000).toISOString(),
  },
];
